# Generated by Django 3.1.6 on 2021-02-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
